### Swagger 접속 주소
GET {{baseUrl}}/swagger-ui/index.html

### 구글 로그인 페이지 연동
GET {{baseUrl}}/oauth2/authorization/google

### 네이버 로그인 페이지 연동
GET {{baseUrl}}/oauth2/authorization/naver

### 카카오 로그인 페이지 연동
GET {{baseUrl}}/oauth2/authorization/kakao
