server:
  port: 9093

spring:
  config:
    import: classpath:application-common.yml
  profiles:
    active: local
    include:
      - oauth
      - swagger

logging:
  level:
    org.springframework: debug

---

spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
#
#springdoc:
#  swagger-ui:
#    enabled: false