server:
  port: 9093
  shutdown: graceful

spring:
  config:
    import: classpath:application-common.yml
  profiles:
    active: dev
    include:
      - oauth
      - swagger

logging:
  level:
    org.springframework: debug

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

#springdoc:
#  swagger-ui:
#    enabled: false