spring:
  profiles:
    active: local

logging:
  level: Debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: ENC(5eKqMRwWm3gu2cWbj7ZDwU6kjns8jc6x5mfhNO2OeGZGA6acOdOGEA==)
    username: ENC(tghQ6A3eYkNGhywrBV2ZTA==)
    password: ENC(sfkTnwAknl+TTzT1SMmuZA==)
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
---
spring:
  config:
    activate:
      on-profile: dev, prod
  datasource:
    url: ENC(0y7YQLK2Ag0ZSBBDbd+kdOHEbppCv1bTrCzThhns4sBW/vAjVbIK6bmDlAkpyo+jtFGgYbpTpLDW8NBIGaj5V+aQ21O94GGv7tecj50QgLSB3WW+sYUkAZDBdRoTfG+i7QOjcOwgVEYckN2+RhKLV5n5DimH+/C0Q43zZULdRzeSOy9YLSaB0lYGHZ0tffh0X368hUHm1JyPKmP6WhYUCw==)
    username: ENC(bWk/QGIPORh8yasR9NSxJA==)
    password: ENC(bVuitv+Tiho4lTO2W5mCTg==)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace