spring:
  profiles:
    active: local

logging:
  level: Debug

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;  # 접속 URL
    username: yj_park  # 사용자 이름 (로그인 시 사용)
    password: 1234     # 사용자 암호 (로그인 시 사용)
    driver-class-name: org.h2.Driver  # h2 드라이버 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://db-lazy.cwn26ebdtrvp.ap-northeast-2.rds.amazonaws.com:3306/lazy_19th?useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: *********
    password: *********
    # driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://db-lazy.cwn26ebdtrvp.ap-northeast-2.rds.amazonaws.com:3306/lazy_19th?useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: *********
    password: *********
    # driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
